version: '3.1'

services:

  web:
    image: ghost:latest
    restart: unless-stopped
    ports:
      - 8083:2368
    volumes:
      - content:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: S3cur3P@ssW0rd!
      database__connection__database: ghost
      url: https://ghost.your-site.com
    networks:
      - public
      - internal
    depends_on:
      - db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ghost.rule=Host(`ghost.your-site.com`)"
        - "traefik.http.routers.ghost.entrypoints=websecure"
        - "traefik.http.routers.ghost.tls=true"
        - "traefik.http.services.ghost.loadbalancer.server.port=2368"
        - "traefik.http.routers.ghost.service=ghost"

  db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: S3cur3P@ssW0rd!
    networks:
      - internal
      
volumes:
  content:
  
networks:
  public:
    external: true
  internal:
    external: false
