version: '3.8'

services:
  db:
    container_name: db
    environment:
      MYSQL_LOG_CONSOLE: "true"
      MYSQL_ROOT_PASSWORD: ${SEAFILE_DB_ROOT_PASSWORD}
    image: mariadb:latest
    networks:
      - backend
    volumes:
      - seafile_db:/var/lib/mysql:rw
    restart: unless-stopped
    
  memcached:
    container_name: memcached
    entrypoint: memcached -m 256
    image: memcached:1.6.17
    networks:
      - backend
    restart: unless-stopped
    
  seafile:
    ports:
      - "8085:80"
    depends_on:
      - db
      - memcached
    environment:
      DB_HOST: db
      DB_ROOT_PASSWD: ${SEAFILE_DB_ROOT_PASSWORD}
      SEAFILE_ADMIN_EMAIL: ${SEAFILE_ADMIN_EMAIL}
      SEAFILE_ADMIN_PASSWORD: ${SEAFILE_ADMIN_PASSWORD}
      SEAFILE_SERVER_HOSTNAME: ${HOST_SEAFILE}.${DOMAIN}
      SEAFILE_SERVER_LETSENCRYPT: "false"
      TIME_ZONE: ${TZ}
    image: seafileltd/seafile-mc:latest
    networks:
      - backend
      - public
    restart: unless-stopped
    volumes:
      - seafile_data:/shared:rw
    cap_add:
      - SYS_ADMIN
    labels:
      - traefik.enable=true
      - traefik.http.routers.seafile.rule=Host(`${HOST_SEAFILE}.${DOMAIN}`)
      - traefik.http.routers.seafile.entrypoints=websecure
      - traefik.http.routers.seafile.tls=true
      - traefik.http.services.seafile.loadbalancer.server.port=80
      - traefik.http.routers.seafile.service=seafile
      
networks:
  public:
    external: true
  backend:
    external: false

volumes:
  seafile_db:
  seafile_data:
